// <auto-generated />
using AAA_ASP.net_core_web_API.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AAA_ASP.net_core_web_API.Migrations
{
    [DbContext(typeof(DatabaseConnection))]
    [Migration("20230317203828_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AAA_ASP.net_core_web_API.Model.Laptop", b =>
                {
                    b.Property<int>("LaptopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LaptopDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LaptopModel")
                        .HasColumnType("int");

                    b.Property<string>("LaptopName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LaptopID");

                    b.ToTable("Laptop");
                });
#pragma warning restore 612, 618
        }
    }
}
